before_script:
    - git clone -b master https://github.com/cirulls/xspec.git /tmp/xspec
    - export SAXON_CP=/tmp/xspec/saxon9he.jar

script:
    - cd test
    - echo "execute XSpec unit tests"
    - bash run-xspec-tests.sh
